name: Go Test

on:
  pull_request:
    branches: 
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20
    - name: Run tests
      run: go test ./...
    - name: Test results
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: "**/report.xml"
